/**
 * A Preview, and what the agent is told about one.
 *
 * A **Preview** is a second varnick launched from a **Worktree** so a Core
 * change can be run before it is merged. The agent asks for one through the
 * `launch_preview` **Custom Tool**; the host spawns it. This module is the
 * Harness's half of that: the tool's shape, the sentences the agent reads back,
 * and the one line each request and answer crosses on.
 *
 * ## There is nothing here to approve, and that is the change
 *
 * A Preview used to run under the policy generated by the tree it was launched
 * from, which is a tree the agent wrote. That is a path from confined to
 * unconfined in three steps — edit `sandbox.ts` in a worktree, call this tool,
 * and the host spawns a varnick whose fence the agent authored, whose own agent
 * then runs under it — and a native dialog stood in it. So this module also held
 * the diff that dialog showed: `fenceHunks`, which filtered a patch down to the
 * paths that decide what an agent may do.
 *
 * The path is closed rather than gated now. **A Preview is confined by the
 * policy in force in the live tree**, whatever is in the Worktree, and its
 * Credential is injected by the parent host rather than read a second time from
 * the Keychain — see `establishSandbox` in ./sandbox.ts, `preview_launch` in
 * src-tauri/src/preview.rs, and
 * docs/adr/0019-a-preview-is-confined-by-the-live-trees-policy.md. With no
 * escalation to approve there is no dialog, no `declined` outcome, and no diff
 * to compute: `fenceHunks` and `readFenceDiff` went with it. What is left of the
 * Fence is `./fence.ts`, which the pending-worktree list and the diff view still
 * ask.
 *
 * ## Nothing here spawns anything
 *
 * The spawn is `src-tauri/src/preview.rs`, because a confined process cannot
 * open a window. What is here is what can be decided from text.
 */

// ---------------------------------------------------------------------------
// What the agent asked for, and what it is told
// ---------------------------------------------------------------------------

/** The Custom Tool's name, as the agent sees it. */
export const LAUNCH_PREVIEW_TOOL = 'launch_preview'

/**
 * What the tool says it does — including the two things it will not do.
 *
 * The refusals are described rather than left to be discovered, because an agent
 * that knows the tool takes a name does not try a path, and a tool call that was
 * never made is the cheapest refusal there is.
 *
 * The last paragraph is the same argument pointed the other way. An agent told
 * that a preview of its own `sandbox.ts` runs under the *live* policy does not
 * spend a Turn wondering why the change it is looking at had no effect — and it
 * is a true sentence about the mechanism rather than an instruction, which is
 * the only kind of sentence a tool description can be trusted to carry.
 */
export const LAUNCH_PREVIEW_DESCRIPTION = [
  'Launch a preview of a git worktree: a second varnick running from it, in its own window,',
  'so a Core change can be run before it is merged. It is a working varnick with an agent of',
  'its own — something to talk to, not a screen to look at.',
  '',
  'Takes the name of a worktree under .claude/worktrees/ — one path component, nothing else.',
  'It is not a path and not a command: an absolute path, anything with a slash in it, and any',
  'name git does not report are all refused. The window is opened by the host, because a',
  'confined process cannot open one.',
  '',
  'Nothing is asked of the developer, and any worktree can be previewed. The preview’s agent',
  'is confined by the sandbox policy in force in the live clone, never by the one in the',
  'worktree, so a change to the policy generator can be run and read there and still decides',
  'nothing until a human merges it.',
].join('\n')

/**
 * What happened to a request for a Preview.
 *
 * The tags `src-tauri/src/preview.rs` writes. Every sentence for them is
 * authored below and selected by the tag, which is the same rule
 * `turnFailureMessage` follows and it is load-bearing for the same reason: the
 * host holds the Credential, and nothing it observed — a path, an OS error, an
 * environment — may become a string the confined agent reads.
 */
export const PREVIEW_OUTCOMES = [
  'launched',
  'unknown-worktree',
  'no-worktrees',
  'no-launch',
] as const

export type PreviewOutcome = (typeof PREVIEW_OUTCOMES)[number]

export function isPreviewOutcome(value: unknown): value is PreviewOutcome {
  return typeof value === 'string' && (PREVIEW_OUTCOMES as readonly string[]).includes(value)
}

/** What to tell the agent, in one sentence, selected by the tag. */
export function previewOutcomeMessage(outcome: PreviewOutcome): string {
  switch (outcome) {
    case 'launched':
      return 'A preview of that worktree is starting in its own window, on its own port, with its own session.'
    case 'unknown-worktree':
      return 'That is not the name of a worktree under .claude/worktrees/. The name is one path component — not a path, not an absolute path, and not the live clone. Create the worktree first, or name one that exists.'
    case 'no-worktrees':
      return 'The host could not ask git what worktrees exist, so nothing could be checked and nothing was launched.'
    case 'no-launch':
      return 'The worktree was found and the preview did not start. Nothing is running from it.'
  }
}

/**
 * The tool's answer, as the agent reads it.
 *
 * A sentence and a flag. The flag is what makes "there is no window" a fact the
 * agent can act on rather than prose it has to interpret: every outcome but one
 * means nothing is running, and an agent that went on to describe what the
 * preview shows would be describing a window that was never opened.
 */
export function previewToolResult(outcome: PreviewOutcome): {
  readonly launched: boolean
  readonly text: string
} {
  return { launched: outcome === 'launched', text: previewOutcomeMessage(outcome) }
}

/**
 * One request for a Preview, as one line on the agent host's stdout.
 *
 * The second shape on a pipe that carries Turn events, told apart by which id it
 * names: a Turn event names a `turnId` and this names a `requestId`. `preview_request_of`
 * in src-tauri/src/preview.rs is the reader, and `agent_event_of` beside it
 * drops this line rather than delivering it to a Turn.
 *
 * Two fields, because there is nothing else a Preview needs. There is
 * deliberately no field for a command, a path, a port or an environment: the
 * host decides all four, and a field the agent could fill would be the shell out
 * of the Sandbox this whole tool is shaped to avoid.
 */
export function encodePreviewRequest(requestId: string, worktree: string): string {
  return `${JSON.stringify({ kind: 'launch-preview', requestId, worktree })}\n`
}
